// Code generated by the Encore 1.48.8 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly apps: apps.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly contact: contact.ServiceClient
    public readonly developer: developer.ServiceClient
    public readonly legal: legal.ServiceClient
    public readonly users: users.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.apps = new apps.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.contact = new contact.ServiceClient(base)
        this.developer = new developer.ServiceClient(base)
        this.legal = new legal.ServiceClient(base)
        this.users = new users.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createReview as api_apps_create_review_createReview } from "~backend/apps/create_review";
import { downloadApp as api_apps_download_app_downloadApp } from "~backend/apps/download_app";
import { getApp as api_apps_get_app_getApp } from "~backend/apps/get_app";
import { getFeaturedApps as api_apps_get_featured_apps_getFeaturedApps } from "~backend/apps/get_featured_apps";
import { listApps as api_apps_list_apps_listApps } from "~backend/apps/list_apps";
import { listCategories as api_apps_list_categories_listCategories } from "~backend/apps/list_categories";
import { listReviews as api_apps_list_reviews_listReviews } from "~backend/apps/list_reviews";

export namespace apps {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createReview = this.createReview.bind(this)
            this.downloadApp = this.downloadApp.bind(this)
            this.getApp = this.getApp.bind(this)
            this.getFeaturedApps = this.getFeaturedApps.bind(this)
            this.listApps = this.listApps.bind(this)
            this.listCategories = this.listCategories.bind(this)
            this.listReviews = this.listReviews.bind(this)
        }

        /**
         * Creates a new review for an app.
         */
        public async createReview(params: RequestType<typeof api_apps_create_review_createReview>): Promise<ResponseType<typeof api_apps_create_review_createReview>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                comment: params.comment,
                rating:  params.rating,
                title:   params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/apps/${encodeURIComponent(params.slug)}/reviews`, {headers, method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_apps_create_review_createReview>
        }

        /**
         * Initiates an app download and tracks the download event.
         */
        public async downloadApp(params: RequestType<typeof api_apps_download_app_downloadApp>): Promise<ResponseType<typeof api_apps_download_app_downloadApp>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization:     params.authorization,
                "user-agent":      params["user_agent"],
                "x-forwarded-for": params["x_forwarded_for"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/apps/${encodeURIComponent(params.slug)}/download`, {headers, method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_apps_download_app_downloadApp>
        }

        /**
         * Retrieves a single app by its slug.
         */
        public async getApp(params: { slug: string }): Promise<ResponseType<typeof api_apps_get_app_getApp>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/apps/${encodeURIComponent(params.slug)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_apps_get_app_getApp>
        }

        /**
         * Retrieves featured, trending, and new apps for the homepage.
         */
        public async getFeaturedApps(): Promise<ResponseType<typeof api_apps_get_featured_apps_getFeaturedApps>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/apps/featured`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_apps_get_featured_apps_getFeaturedApps>
        }

        /**
         * Retrieves all published apps with filtering and sorting options.
         */
        public async listApps(params: RequestType<typeof api_apps_list_apps_listApps>): Promise<ResponseType<typeof api_apps_list_apps_listApps>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:    params.category,
                featured:    params.featured === undefined ? undefined : String(params.featured),
                limit:       params.limit === undefined ? undefined : String(params.limit),
                offset:      params.offset === undefined ? undefined : String(params.offset),
                search:      params.search,
                sort:        params.sort === undefined ? undefined : String(params.sort),
                "web3_only": params["web3_only"] === undefined ? undefined : String(params["web3_only"]),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/apps`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_apps_list_apps_listApps>
        }

        /**
         * Retrieves all app categories.
         */
        public async listCategories(): Promise<ResponseType<typeof api_apps_list_categories_listCategories>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/categories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_apps_list_categories_listCategories>
        }

        /**
         * Retrieves reviews for a specific app.
         */
        public async listReviews(params: RequestType<typeof api_apps_list_reviews_listReviews>): Promise<ResponseType<typeof api_apps_list_reviews_listReviews>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/apps/${encodeURIComponent(params.slug)}/reviews`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_apps_list_reviews_listReviews>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { login as api_auth_login_login } from "~backend/auth/login";
import { logout as api_auth_logout_logout } from "~backend/auth/logout";
import { me as api_auth_me_me } from "~backend/auth/me";
import { signup as api_auth_signup_signup } from "~backend/auth/signup";
import { getUserDownloads as api_auth_user_downloads_getUserDownloads } from "~backend/auth/user_downloads";
import {
    addToWishlist as api_auth_wishlist_addToWishlist,
    getWishlist as api_auth_wishlist_getWishlist,
    removeFromWishlist as api_auth_wishlist_removeFromWishlist
} from "~backend/auth/wishlist";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addToWishlist = this.addToWishlist.bind(this)
            this.getUserDownloads = this.getUserDownloads.bind(this)
            this.getWishlist = this.getWishlist.bind(this)
            this.login = this.login.bind(this)
            this.logout = this.logout.bind(this)
            this.me = this.me.bind(this)
            this.removeFromWishlist = this.removeFromWishlist.bind(this)
            this.signup = this.signup.bind(this)
        }

        /**
         * Adds an app to the user's wishlist.
         */
        public async addToWishlist(params: RequestType<typeof api_auth_wishlist_addToWishlist>): Promise<ResponseType<typeof api_auth_wishlist_addToWishlist>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/wishlist/${encodeURIComponent(params.app_id)}`, {headers, method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_wishlist_addToWishlist>
        }

        /**
         * Gets the current user's download history.
         */
        public async getUserDownloads(params: RequestType<typeof api_auth_user_downloads_getUserDownloads>): Promise<ResponseType<typeof api_auth_user_downloads_getUserDownloads>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/downloads`, {headers, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_user_downloads_getUserDownloads>
        }

        /**
         * Gets the current user's wishlist.
         */
        public async getWishlist(params: RequestType<typeof api_auth_wishlist_getWishlist>): Promise<ResponseType<typeof api_auth_wishlist_getWishlist>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/wishlist`, {headers, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_wishlist_getWishlist>
        }

        /**
         * Authenticates a user and creates a session.
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Logs out a user by invalidating their session.
         */
        public async logout(params: RequestType<typeof api_auth_logout_logout>): Promise<ResponseType<typeof api_auth_logout_logout>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/logout`, {headers, method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_logout_logout>
        }

        /**
         * Gets the current user's profile information.
         */
        public async me(params: RequestType<typeof api_auth_me_me>): Promise<ResponseType<typeof api_auth_me_me>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/me`, {headers, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_me_me>
        }

        /**
         * Removes an app from the user's wishlist.
         */
        public async removeFromWishlist(params: RequestType<typeof api_auth_wishlist_removeFromWishlist>): Promise<ResponseType<typeof api_auth_wishlist_removeFromWishlist>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/wishlist/${encodeURIComponent(params.app_id)}`, {headers, method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_wishlist_removeFromWishlist>
        }

        /**
         * Creates a new user account.
         */
        public async signup(params: RequestType<typeof api_auth_signup_signup>): Promise<ResponseType<typeof api_auth_signup_signup>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/signup`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_signup_signup>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { send as api_contact_send_send } from "~backend/contact/send";

export namespace contact {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.send = this.send.bind(this)
        }

        /**
         * Sends a contact message.
         */
        public async send(params: RequestType<typeof api_contact_send_send>): Promise<ResponseType<typeof api_contact_send_send>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/contact`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_contact_send_send>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getDashboard as api_developer_dashboard_getDashboard } from "~backend/developer/dashboard";
import { submitApp as api_developer_submit_app_submitApp } from "~backend/developer/submit_app";

export namespace developer {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getDashboard = this.getDashboard.bind(this)
            this.submitApp = this.submitApp.bind(this)
        }

        /**
         * Gets developer dashboard data.
         */
        public async getDashboard(params: RequestType<typeof api_developer_dashboard_getDashboard>): Promise<ResponseType<typeof api_developer_dashboard_getDashboard>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/developer/dashboard`, {headers, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_developer_dashboard_getDashboard>
        }

        /**
         * Submits a new app for review.
         */
        public async submitApp(params: RequestType<typeof api_developer_submit_app_submitApp>): Promise<ResponseType<typeof api_developer_submit_app_submitApp>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "apk_size":               params["apk_size"],
                "apk_url":                params["apk_url"],
                "banner_url":             params["banner_url"],
                "blockchain_networks":    params["blockchain_networks"],
                "category_id":            params["category_id"],
                description:              params.description,
                "github_repo":            params["github_repo"],
                "icon_url":               params["icon_url"],
                "is_web3":                params["is_web3"],
                "min_android_version":    params["min_android_version"],
                name:                     params.name,
                "package_name":           params["package_name"],
                permissions:              params.permissions,
                screenshots:              params.screenshots,
                "short_description":      params["short_description"],
                "target_android_version": params["target_android_version"],
                version:                  params.version,
                "wallet_required":        params["wallet_required"],
                "website_url":            params["website_url"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/developer/submit`, {headers, method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_developer_submit_app_submitApp>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getDocument as api_legal_documents_getDocument,
    listDocuments as api_legal_documents_listDocuments
} from "~backend/legal/documents";

export namespace legal {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getDocument = this.getDocument.bind(this)
            this.listDocuments = this.listDocuments.bind(this)
        }

        /**
         * Gets a specific legal document by type.
         */
        public async getDocument(params: { document_type: string }): Promise<ResponseType<typeof api_legal_documents_getDocument>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/legal/${encodeURIComponent(params.document_type)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_legal_documents_getDocument>
        }

        /**
         * Lists all active legal documents.
         */
        public async listDocuments(): Promise<ResponseType<typeof api_legal_documents_listDocuments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/legal`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_legal_documents_listDocuments>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getProfile as api_users_profile_getProfile,
    updateProfile as api_users_profile_updateProfile
} from "~backend/users/profile";
import {
    getSettings as api_users_settings_getSettings,
    updateSettings as api_users_settings_updateSettings
} from "~backend/users/settings";

export namespace users {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getProfile = this.getProfile.bind(this)
            this.getSettings = this.getSettings.bind(this)
            this.updateProfile = this.updateProfile.bind(this)
            this.updateSettings = this.updateSettings.bind(this)
        }

        /**
         * Gets a user's profile information.
         */
        public async getProfile(params: RequestType<typeof api_users_profile_getProfile>): Promise<ResponseType<typeof api_users_profile_getProfile>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            const query = makeRecord<string, string | string[]>({
                "user_id": params["user_id"] === undefined ? undefined : String(params["user_id"]),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/profile`, {headers, query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_profile_getProfile>
        }

        /**
         * Gets the current user's settings.
         */
        public async getSettings(params: RequestType<typeof api_users_settings_getSettings>): Promise<ResponseType<typeof api_users_settings_getSettings>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/settings`, {headers, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_settings_getSettings>
        }

        /**
         * Updates the current user's profile.
         */
        public async updateProfile(params: RequestType<typeof api_users_profile_updateProfile>): Promise<ResponseType<typeof api_users_profile_updateProfile>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                bio:              params.bio,
                "github_handle":  params["github_handle"],
                location:         params.location,
                "public_profile": params["public_profile"],
                "show_downloads": params["show_downloads"],
                "show_email":     params["show_email"],
                "show_reviews":   params["show_reviews"],
                "twitter_handle": params["twitter_handle"],
                website:          params.website,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/profile`, {headers, method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_profile_updateProfile>
        }

        /**
         * Updates the current user's settings.
         */
        public async updateSettings(params: RequestType<typeof api_users_settings_updateSettings>): Promise<ResponseType<typeof api_users_settings_updateSettings>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "accessibility_high_contrast": params["accessibility_high_contrast"],
                "accessibility_large_text":    params["accessibility_large_text"],
                "email_notifications":         params["email_notifications"],
                language:                      params.language,
                "marketing_emails":            params["marketing_emails"],
                "push_notifications":          params["push_notifications"],
                "theme_preference":            params["theme_preference"],
                timezone:                      params.timezone,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/settings`, {headers, method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_settings_updateSettings>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.8)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
